name: "Deps: show new dependencies metadata"
on:
  - pull_request

jobs:
  deps_new_dependencies_advisor:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo for a local instance"
        uses: actions/checkout@v2
        
      - name: "Deps: show new dependencies metadata"
        uses: lirantal/github-action-new-dependencies-advisor@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
