name: Build Dev

on:
    - workflow_dispatch
    - push

permissions:
    contents: write

jobs:
    dev-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: dev
            - uses: actions/setup-node@v3
              with:
                  node-version: 21
                  cache: 'npm'

            - name: Install Dependencies
              run: npm ci

            - name: Build Dev
              run: bash ./build.bash build

            - name: Format
              run: |
                  bash ./build.bash format

            - name: 'Make Save Directories'
              run: |
                  mkdir ../temp_dir/

            - name: Save Files
              run: |
                  cp -R ${{ github.workspace }}/build/ ../temp_dir/
                  cp ${{ github.workspace }}/package.json ../temp_dir/package.json
                  cp ${{ github.workspace }}/README.md ../temp_dir/README.md
                  cp ${{ github.workspace }}/LICENSE ../temp_dir/LICENSE

            - name: Checkout Dev Build Branch
              uses: actions/checkout@v2
              with:
                  ref: dev-build

            - name: Move Files
              run: |
                  rm -rf ./*
                  mv ../temp_dir/* ./

            - name: Commit Changes
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "actions@github.com"
                  git add .
                  git commit -m "Update Dev Build (#${GITHUB_SHA})"
                  git push origin dev-build
