name: Generate Docs

on:
    - workflow_dispatch

permissions:
    actions: write

jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: main
            - uses: actions/setup-node@v3
              with:
                  node-version: 21
                  cache: 'npm'

            - name: Install Dependencies
              run: npm ci

            - name: Build Docs
              run: bash ./build.bash docs

            - name: Checkout Docs Branch
              uses: actions/checkout@v2
              with:
                  ref: docs

            - name: Copy Docs
              run: |
                  cp -R ${{ github.workspace }}/docs/ docs/

            - name: Replace Docs
              run: |
                  rm -rf docs
                  mv ${{ github.workspace }}/docs/ docs/

            - name: Commit Changes
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "actions@github.com"
                  git add .
                  git commit -m "Update Docs"
                  git push origin docs
